name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE_NAME }}:latest .

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE_NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e  # Exit on error

            echo "Stopping and removing old container if exists..."
            docker stop ${{ secrets.CONTAINER_NAME }} || echo "⚠ No container running"
            docker rm ${{ secrets.CONTAINER_NAME }} || echo "⚠ No container to remove"

            echo "Pruning unused Docker images..."
            docker image prune -af

            echo "Running new container..."
            docker run -d --restart unless-stopped -p 4000:4000 --name ${{ secrets.CONTAINER_NAME }} \
              ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGE_NAME }}:latest

            echo "✅ Deployment successful!"
